### ISSUE TITLE
NoClassDefFoundError: org.simpleframework.xml.core.Persister

### ISSUE THREAD

**Issue by jgcorrales** [ngallagher/simplexml#8]
My app, 
compileSdkVersion 23
minSdkVersion 15

added library simplexml.2.7.1 work fine but from added library ExoPlayer to return 

FATAL EXCEPTION: main
                                                                   Process: com.m4v.megacine_ar, PID: 9711
                                                                   java.lang.NoClassDefFoundError: org.simpleframework.xml.core.Persister
                                                                       at com.gwella.cinetotal.Web.XmlRequest.<init>(XmlRequest.java:33)
                                                                       at com.gwella.cinetotal.UI.SplashActivity.onCreate(SplashActivity.java:46)
                                                                       at android.app.Activity.performCreate(Activity.java:5458)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:146)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                       at dalvik.system.NativeStart.main(Native Method) 

`dependencies {
    compile fileTree(dir: 'lib', include: ['*.jar'])
    testCompile ('junit:junit:4.12')
    compile ('com.android.support:appcompat-v7:23.2.0')
    compile ('com.android.support:design:23.2.0')
    compile ('com.android.support:cardview-v7:23.2.0')
    compile ('com.nineoldandroids:library:2.4.0')
    compile ('com.mcxiaoke.volley:library:1.0.19')
    compile ('com.google.android.exoplayer:exoplayer:r1.5.6')
    compile ('org.simpleframework:simple-xml:2.7.1') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    compile ('com.github.moondroid.coverflow:library:1.0')
    compile ('com.sothree.slidinguppanel:library:3.2.0')
    compile ('com.android.support:recyclerview-v7:23.2.0')
    compile ('me.grantland:autofittextview:0.2.+')
    compile ('com.google.android.gms:play-services-analytics:8.1.0')
    compile ('org.lucasr.twowayview:twowayview:0.1.4')
    compile ('com.google.android.gms:play-services:8.1.0')
    compile ('me.relex:circleindicator:1.1.8@aar')
    compile ('com.google.android.gms:play-services-ads:8.1.0')
    compile ('com.google.android.gms:play-services-identity:8.1.0')
    compile ('com.google.android.gms:play-services-gcm:8.1.0')
}`

I want a solution, please, don't working in sdkversion  =< 21.
I took 2 days with her.

**Comment by Kisty** [comment]
Have you tried doing a clean build?

In Android Studio 2.0:
 _Run_ > _Clean and run_

Older versions:
_Build_ > _Rebuild project_

**Comment by sam-almighty** [comment]
Any resolutions here? I have similar issues.
